model_train_type = "sd-lora"
pretrained_model_name_or_path = "1"
v2 = false
train_data_dir = "2"
prior_loss_weight = 1
resolution = "512,512"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1_024
bucket_reso_steps = 64
output_name = "3"
output_dir = "5"
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 1
max_train_epochs = 10
train_batch_size = 1
gradient_checkpointing = true
gradient_accumulation_steps = 2
network_train_unet_only = false
network_train_text_encoder_only = false
learning_rate = 1
unet_lr = 1
text_encoder_lr = 1
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1
optimizer_type = "Prodigy"
network_module = "networks.lora"
network_dim = 64
network_alpha = 32
sample_prompts = "(masterpiece, best quality:1.2), --n lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry,  --w 512  --h 512  --l 7  --s 24  --d 1337"
sample_sampler = "euler"
sample_every_n_epochs = 1
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = true
weighted_captions = false
keep_tokens = 0
max_token_length = 255
seed = 1_337
clip_skip = 2
mixed_precision = "fp16"
full_fp16 = false
full_bf16 = false
xformers = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = false
cache_text_encoder_outputs_to_disk = false
persistent_data_loader_workers = true
network_args = [
  "down_lr_weight=1,1,1,1,1,1,0,0,0,0,0,0",
  "mid_lr_weight=1",
  "up_lr_weight=1,1,1,1,1,1,0,0,0,0,0,0",
  "block_lr_zero_threshold=0"
]
optimizer_args = [
  "decouple=True",
  "weight_decay=0.01",
  "use_bias_correction=True",
  "d_coef=2.0",
  "d0=9e-7"
]
